version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube -Dsonar.projectKey="eyrockscript_jasypt-api" -Dsonar.organization="eyrockscript" -Dsonar.host.url="https://sonarcloud.io"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
